<?php
/**
 * Created by PhpStorm.
 * User: 357397264@qq.com
 * Date: 2018/8/3
 * Time: 下午2:16
 */

namespace app\sys\controller;


use think\Controller;

class BizController extends Controller
{

    /**
     * 模板
     * @var string
     */
    protected static $template;


    /**
     *
     */
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
    }



    public function fetch($template = '', $vars = [], $replace = [], $config = [])
    {
        if( !empty(self::$template) ){
            $template = self::$template;
        }
        return parent::fetch($template, $vars, $replace, $config); // TODO: Change the autogenerated stub
    }


    /**
     * 设置模板
     * @param $template
     */
    public static function template($template)
    {
        self::$template = $template;
    }

}