<?php
/**
 * Created by PhpStorm.
 * User: 357397264@qq.com
 * Date: 2018/6/13
 * Time: 上午10:07
 */

namespace app\sys\model;


use think\Model;

class FileLibrary extends Model
{

    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->name('sys_file_library');
    }

}