<?php
/**
 * 基础模型控制器
 * Created by PhpStorm.
 * User: phpGhost
 * Date: 2018/8/25
 * Time: 16:09
 */

namespace app\sys\model;

use think\Model as ThinkModel;

/**
 * Class Model
 * @package app\sys\model
 * @method $this set_permanent_where($field, $op = null, $condition = null,$key = '') 设置常驻条件
 *          [ 常驻条件:会一直持续在模型中的查询条件,不会因为一次查询而需要重复设置条件 ]
 * @method $this clear_permanent_where() 清空当前所有常驻条件
 */
class Model extends ThinkModel
{
    use QueryTrait;

    public $table_name;

    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        if( !empty($this->table_name) ){
            $this->name($this->table_name);
        }
    }
}