<?php
/**
 * Created by PhpStorm.
 * User: 357397264@qq.com
 * Date: 2018/7/26
 * Time: 上午11:35
 */

namespace app\sys\model;


use think\db\Query;
use think\Model;

class PluginsConfig extends Model
{

    public static $table_name = 'sys_plugins_config';

    /**
     * @var string
     */
    protected $plugins;


    /**
     * @var string
     */
    protected $library;


    /**
     * 配置名称
     * @var string
     */
    protected $config_name;


    /**
     * @var Query
     */
    protected $config;


    /**
     * 初始化
     */
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->name(self::$table_name);
    }


    /**
     * 设置插件位置
     * @param string $plugins_library
     * @return $this
     */
    public function set_plugins_library(string $plugins_library)
    {
        $plugins_library = explode('/',$plugins_library);
        $this->plugins = $plugins_library[0];
        $this->library = empty($plugins_library[1]) ? '' : $plugins_library[1];
        return $this;
    }


    /**
     * 设置配置名称
     * @param string $name
     * @return $this
     */
    public function configName(string $name)
    {
        $this->config_name = $name;
        return $this;
    }


    /**
     * 获取配置值
     * @return mixed
     */
    public function get_value()
    {
        $config = $this->get_item();
        return $config['value'];
    }


    /**
     * 获取整条配置
     * @return mixed
     */
    public function get_item()
    {
        if ( empty($this->config) ){
            $this->get_config();
        }
        return $this->config;
    }


    /**
     * 获取配置
     * @return mixed
     */
    public function get_config()
    {
        if( empty($this->config) ){
            $this->config = cache('plugins_config_'.$this->plugins.'_'.$this->library.'_'.$this->config_name);
            if( empty($this->config) ){
                $config = $this->where([
                    'plugins'=> $this->plugins,
                    'library' => $this->library,
                    'name' => $this->config_name,
                ])->find();
                $this->config = $config->getData();
                cache('plugins_config_'.$this->plugins.'_'.$this->library.'_'.$this->config_name,$this->config);
            }
        }
        return $this->config;
    }

}